app = 'zariva-backend'
primary_region = 'jnb'

[build]

[env]
  ENVIRONMENT = 'production'
  ALGORITHM = 'HS256'
  ACCESS_TOKEN_EXPIRE_MINUTES = '1440'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[http_service.checks]]
  grace_period = '10s'
  interval = '30s'
  method = 'GET'
  path = '/health'
  timeout = '5s'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
