"""add join_requests table

Revision ID: c61e5e18fefc
Revises: ca610a8bf848
Create Date: 2026-07-10 20:54:17.877329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Reuse the existing requeststatus enum (created by the consent migration) rather
# than re-creating it.
request_status = postgresql.ENUM(
    'pending', 'approved', 'approved_with_modifications', 'declined',
    name='requeststatus', create_type=False,
)


# revision identifiers, used by Alembic.
revision: str = 'c61e5e18fefc'
down_revision: Union[str, None] = 'ca610a8bf848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', request_status, nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('lease_id', sa.Integer(), nullable=True),
    sa.Column('decision_by', sa.String(length=150), nullable=True),
    sa.Column('decision_date', sa.DateTime(), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    op.create_index(op.f('ix_join_requests_id'), 'join_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_join_requests_id'), table_name='join_requests')
    op.drop_table('join_requests')
    # ### end Alembic commands ###
