"""add consent management tables

Revision ID: ca610a8bf848
Revises: 644cbe60d716
Create Date: 2026-05-16 14:40:20.330538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca610a8bf848'
down_revision: Union[str, None] = '644cbe60d716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privacy_notice_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('summary_of_changes', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('notice_version', sa.String(length=10), nullable=False),
    sa.Column('lease_admin_consent', sa.Boolean(), nullable=False),
    sa.Column('communications_consent', sa.Boolean(), nullable=False),
    sa.Column('marketing_consent', sa.Boolean(), nullable=False),
    sa.Column('national_id', sa.String(length=30), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('consented_at', sa.DateTime(), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_consent_records_id'), 'consent_records', ['id'], unique=False)
    op.create_table('data_subject_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.Enum('access', 'rectification', 'erasure', 'portability', 'objection', name='datasubjectrequesttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    op.create_table('alteration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('description_of_works', sa.Text(), nullable=False),
    sa.Column('contractor_name', sa.String(length=150), nullable=True),
    sa.Column('contractor_contact', sa.String(length=100), nullable=True),
    sa.Column('estimated_start_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_duration', sa.String(length=100), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'approved_with_modifications', 'declined', name='requeststatus'), nullable=False),
    sa.Column('decision_by', sa.String(length=150), nullable=True),
    sa.Column('decision_date', sa.DateTime(), nullable=True),
    sa.Column('modification_conditions', sa.Text(), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    op.create_table('guarantor_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('national_id', sa.String(length=30), nullable=False),
    sa.Column('relationship_to_tenant', sa.String(length=100), nullable=False),
    sa.Column('employer_occupation', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('physical_address', sa.Text(), nullable=True),
    sa.Column('data_processing_consent', sa.Boolean(), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('witness_name', sa.String(length=150), nullable=True),
    sa.Column('witness_id', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    op.create_table('pet_consent_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('additional_deposit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'approved_with_modifications', 'declined', name='requeststatus'), nullable=False),
    sa.Column('decision_by', sa.String(length=150), nullable=True),
    sa.Column('decision_date', sa.DateTime(), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    op.create_table('sublet_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('subtenant_name', sa.String(length=150), nullable=False),
    sa.Column('subtenant_id_no', sa.String(length=30), nullable=False),
    sa.Column('proposed_commencement', sa.DateTime(), nullable=False),
    sa.Column('proposed_duration', sa.String(length=100), nullable=False),
    sa.Column('monthly_rent_to_subtenant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purpose', sa.Enum('full_sublet', 'room_only', 'full_assignment', name='subletpurpose'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'approved_with_modifications', 'declined', name='requeststatus'), nullable=False),
    sa.Column('decision_by', sa.String(length=150), nullable=True),
    sa.Column('decision_date', sa.DateTime(), nullable=True),
    sa.Column('additional_conditions', sa.Text(), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    op.create_table('pet_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('animal_type', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('vaccinated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['pet_consent_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet_details')
    op.drop_table('sublet_requests')
    op.drop_table('pet_consent_requests')
    op.drop_table('guarantor_consents')
    op.drop_table('alteration_requests')
    op.drop_table('data_subject_requests')
    op.drop_index(op.f('ix_consent_records_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_table('privacy_notice_versions')
    # ### end Alembic commands ###
