export const landlordData = {
  overview: {
    totalProperties: 12,
    totalUnits: 48,
    occupiedUnits: 42,
    occupancyRate: 87.5,
    monthlyRevenue: 2450000,
    yearlyRevenue: 28500000,
    pendingMaintenance: 5,
    activeTenants: 42,
    revenueGrowth: 12.5,
    newTenantsThisMonth: 3,
  },

  properties: [
    {
      id: 1,
      name: "Kilimani Apartments",
      location: "Kilimani, Nairobi",
      units: 12,
      occupiedUnits: 11,
      occupancyRate: 91.7,
      monthlyIncome: 540000,
      image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=400",
      type: "Apartment",
      status: "active",
    },
    {
      id: 2,
      name: "Westlands Towers",
      location: "Westlands, Nairobi",
      units: 8,
      occupiedUnits: 8,
      occupancyRate: 100,
      monthlyIncome: 720000,
      image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400",
      type: "Commercial",
      status: "active",
    },
    {
      id: 3,
      name: "Karen Villas",
      location: "Karen, Nairobi",
      units: 6,
      occupiedUnits: 5,
      occupancyRate: 83.3,
      monthlyIncome: 450000,
      image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400",
      type: "Villa",
      status: "active",
    },
    {
      id: 4,
      name: "Lavington Heights",
      location: "Lavington, Nairobi",
      units: 10,
      occupiedUnits: 9,
      occupancyRate: 90,
      monthlyIncome: 680000,
      image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400",
      type: "Apartment",
      status: "active",
    },
    {
      id: 5,
      name: "Parklands Plaza",
      location: "Parklands, Nairobi",
      units: 12,
      occupiedUnits: 9,
      occupancyRate: 75,
      monthlyIncome: 360000,
      image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400",
      type: "Mixed Use",
      status: "maintenance",
    },
  ],

  revenueData: [
    { month: "Sep", revenue: 2100000, expenses: 450000 },
    { month: "Oct", revenue: 2250000, expenses: 480000 },
    { month: "Nov", revenue: 2300000, expenses: 490000 },
    { month: "Dec", revenue: 2400000, expenses: 520000 },
    { month: "Jan", revenue: 2350000, expenses: 500000 },
    { month: "Feb", revenue: 2450000, expenses: 510000 },
  ],

  recentActivity: [
    {
      id: 1,
      type: "payment",
      tenant: "John Kamau",
      property: "Kilimani Apartments",
      unit: "A12",
      amount: 45000,
      date: new Date(2026, 2, 18),
      status: "completed",
    },
    {
      id: 2,
      type: "maintenance",
      tenant: "Mary Wanjiru",
      property: "Westlands Towers",
      unit: "B05",
      description: "Plumbing issue in kitchen",
      date: new Date(2026, 2, 17),
      status: "pending",
    },
    {
      id: 3,
      type: "payment",
      tenant: "David Ochieng",
      property: "Karen Villas",
      unit: "V03",
      amount: 75000,
      date: new Date(2026, 2, 17),
      status: "completed",
    },
    {
      id: 4,
      type: "lease_renewal",
      tenant: "Sarah Akinyi",
      property: "Lavington Heights",
      unit: "C08",
      date: new Date(2026, 2, 16),
      status: "pending",
    },
    {
      id: 5,
      type: "payment",
      tenant: "Peter Mwangi",
      property: "Parklands Plaza",
      unit: "D02",
      amount: 30000,
      date: new Date(2026, 2, 15),
      status: "completed",
    },
    {
      id: 6,
      type: "maintenance",
      tenant: "Grace Njeri",
      property: "Kilimani Apartments",
      unit: "A07",
      description: "Air conditioning not working",
      date: new Date(2026, 2, 15),
      status: "in_progress",
    },
  ],

  maintenanceRequests: [
    {
      id: 1,
      property: "Westlands Towers",
      unit: "B05",
      tenant: "Mary Wanjiru",
      issue: "Plumbing issue in kitchen",
      priority: "high",
      status: "pending",
      date: new Date(2026, 2, 17),
    },
    {
      id: 2,
      property: "Kilimani Apartments",
      unit: "A07",
      tenant: "Grace Njeri",
      issue: "Air conditioning not working",
      priority: "medium",
      status: "in_progress",
      date: new Date(2026, 2, 15),
    },
    {
      id: 3,
      property: "Karen Villas",
      unit: "V02",
      tenant: "James Oloo",
      issue: "Broken window in bedroom",
      priority: "high",
      status: "pending",
      date: new Date(2026, 2, 14),
    },
    {
      id: 4,
      property: "Parklands Plaza",
      unit: "D05",
      tenant: "Ann Muthoni",
      issue: "Electrical outlet not working",
      priority: "low",
      status: "pending",
      date: new Date(2026, 2, 13),
    },
    {
      id: 5,
      property: "Lavington Heights",
      unit: "C03",
      tenant: "Thomas Kipchoge",
      issue: "Water heater malfunction",
      priority: "high",
      status: "in_progress",
      date: new Date(2026, 2, 12),
    },
  ],
};
