export const landlordData = {
  profile: {
    name: "Matty Otieno",
    email: "matty@zariva.com",
    phone: "+254 722 123 456",
    avatar: null,
    company: "Zariva Africa Properties Ltd",
    location: "Nairobi, Kenya",
    joinDate: new Date(2022, 3, 1),
  },
  overview: {
    totalProperties: 12,
    totalUnits: 48,
    occupiedUnits: 42,
    occupancyRate: 87.5,
    monthlyRevenue: 2450000,
    yearlyRevenue: 28500000,
    pendingMaintenance: 5,
    activeTenants: 42,
    revenueGrowth: 12.5,
    newTenantsThisMonth: 3,
  },

  properties: [
    {
      id: 1,
      name: "Kilimani Apartments",
      location: "Kilimani, Nairobi",
      units: 12,
      occupiedUnits: 11,
      occupancyRate: 91.7,
      monthlyIncome: 540000,
      image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=400",
      type: "Apartment",
      status: "active",
    },
    {
      id: 2,
      name: "Westlands Towers",
      location: "Westlands, Nairobi",
      units: 8,
      occupiedUnits: 8,
      occupancyRate: 100,
      monthlyIncome: 720000,
      image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400",
      type: "Commercial",
      status: "active",
    },
    {
      id: 3,
      name: "Karen Villas",
      location: "Karen, Nairobi",
      units: 6,
      occupiedUnits: 5,
      occupancyRate: 83.3,
      monthlyIncome: 450000,
      image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400",
      type: "Villa",
      status: "active",
    },
    {
      id: 4,
      name: "Lavington Heights",
      location: "Lavington, Nairobi",
      units: 10,
      occupiedUnits: 9,
      occupancyRate: 90,
      monthlyIncome: 680000,
      image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400",
      type: "Apartment",
      status: "active",
    },
    {
      id: 5,
      name: "Parklands Plaza",
      location: "Parklands, Nairobi",
      units: 12,
      occupiedUnits: 9,
      occupancyRate: 75,
      monthlyIncome: 360000,
      image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400",
      type: "Mixed Use",
      status: "maintenance",
    },
  ],

  revenueData: [
    { month: "Sep", revenue: 2100000, expenses: 450000 },
    { month: "Oct", revenue: 2250000, expenses: 480000 },
    { month: "Nov", revenue: 2300000, expenses: 490000 },
    { month: "Dec", revenue: 2400000, expenses: 520000 },
    { month: "Jan", revenue: 2350000, expenses: 500000 },
    { month: "Feb", revenue: 2450000, expenses: 510000 },
  ],

  recentActivity: [
    {
      id: 1,
      type: "payment",
      tenant: "John Kamau",
      property: "Kilimani Apartments",
      unit: "A12",
      amount: 45000,
      date: new Date(2026, 2, 18),
      status: "completed",
    },
    {
      id: 2,
      type: "maintenance",
      tenant: "Mary Wanjiru",
      property: "Westlands Towers",
      unit: "B05",
      description: "Plumbing issue in kitchen",
      date: new Date(2026, 2, 17),
      status: "pending",
    },
    {
      id: 3,
      type: "payment",
      tenant: "David Ochieng",
      property: "Karen Villas",
      unit: "V03",
      amount: 75000,
      date: new Date(2026, 2, 17),
      status: "completed",
    },
    {
      id: 4,
      type: "lease_renewal",
      tenant: "Sarah Akinyi",
      property: "Lavington Heights",
      unit: "C08",
      date: new Date(2026, 2, 16),
      status: "pending",
    },
    {
      id: 5,
      type: "payment",
      tenant: "Peter Mwangi",
      property: "Parklands Plaza",
      unit: "D02",
      amount: 30000,
      date: new Date(2026, 2, 15),
      status: "completed",
    },
    {
      id: 6,
      type: "maintenance",
      tenant: "Grace Njeri",
      property: "Kilimani Apartments",
      unit: "A07",
      description: "Air conditioning not working",
      date: new Date(2026, 2, 15),
      status: "in_progress",
    },
  ],

  maintenanceRequests: [
    {
      id: 1,
      property: "Westlands Towers",
      unit: "B05",
      tenant: "Mary Wanjiru",
      issue: "Plumbing issue in kitchen",
      priority: "high",
      status: "pending",
      date: new Date(2026, 2, 17),
    },
    {
      id: 2,
      property: "Kilimani Apartments",
      unit: "A07",
      tenant: "Grace Njeri",
      issue: "Air conditioning not working",
      priority: "medium",
      status: "in_progress",
      date: new Date(2026, 2, 15),
    },
    {
      id: 3,
      property: "Karen Villas",
      unit: "V02",
      tenant: "James Oloo",
      issue: "Broken window in bedroom",
      priority: "high",
      status: "pending",
      date: new Date(2026, 2, 14),
    },
    {
      id: 4,
      property: "Parklands Plaza",
      unit: "D05",
      tenant: "Ann Muthoni",
      issue: "Electrical outlet not working",
      priority: "low",
      status: "pending",
      date: new Date(2026, 2, 13),
    },
    {
      id: 5,
      property: "Lavington Heights",
      unit: "C03",
      tenant: "Thomas Kipchoge",
      issue: "Water heater malfunction",
      priority: "high",
      status: "in_progress",
      date: new Date(2026, 2, 12),
    },
  ],

  tenants: [
    {
      id: 1,
      name: "John Kamau",
      email: "john.kamau@email.com",
      phone: "+254 712 000 001",
      property: "Kilimani Apartments",
      propertyId: 1,
      unit: "A12",
      unitType: "3BR",
      monthlyRent: 55000,
      leaseStart: new Date(2025, 0, 1),
      leaseEnd: new Date(2026, 11, 31),
      leaseStatus: "active",
      paymentStatus: "paid",
      balance: 0,
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
    },
    {
      id: 2,
      name: "Mary Wanjiru",
      email: "mary.wanjiru@email.com",
      phone: "+254 722 000 002",
      property: "Westlands Towers",
      propertyId: 2,
      unit: "B05",
      unitType: "2BR",
      monthlyRent: 90000,
      leaseStart: new Date(2024, 6, 1),
      leaseEnd: new Date(2026, 5, 30),
      leaseStatus: "ending",
      paymentStatus: "paid",
      balance: 0,
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
    },
    {
      id: 3,
      name: "David Ochieng",
      email: "david.ochieng@email.com",
      phone: "+254 733 000 003",
      property: "Karen Villas",
      propertyId: 3,
      unit: "V03",
      unitType: "4BR Villa",
      monthlyRent: 75000,
      leaseStart: new Date(2024, 2, 1),
      leaseEnd: new Date(2026, 1, 28),
      leaseStatus: "active",
      paymentStatus: "paid",
      balance: 0,
      avatar: null,
    },
    {
      id: 4,
      name: "Sarah Akinyi",
      email: "sarah.akinyi@email.com",
      phone: "+254 712 345 678",
      property: "Lavington Heights",
      propertyId: 4,
      unit: "C08",
      unitType: "2BR",
      monthlyRent: 68000,
      leaseStart: new Date(2025, 0, 1),
      leaseEnd: new Date(2026, 11, 31),
      leaseStatus: "active",
      paymentStatus: "overdue",
      balance: 68000,
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100",
    },
    {
      id: 5,
      name: "Peter Mwangi",
      email: "peter.mwangi@email.com",
      phone: "+254 700 000 005",
      property: "Parklands Plaza",
      propertyId: 5,
      unit: "D02",
      unitType: "Office",
      monthlyRent: 30000,
      leaseStart: new Date(2025, 3, 1),
      leaseEnd: new Date(2026, 2, 31),
      leaseStatus: "ending",
      paymentStatus: "due_soon",
      balance: 30000,
      avatar: null,
    },
    {
      id: 6,
      name: "Grace Njeri",
      email: "grace.njeri@email.com",
      phone: "+254 711 000 006",
      property: "Kilimani Apartments",
      propertyId: 1,
      unit: "A07",
      unitType: "2BR",
      monthlyRent: 45000,
      leaseStart: new Date(2024, 8, 1),
      leaseEnd: new Date(2026, 7, 31),
      leaseStatus: "active",
      paymentStatus: "paid",
      balance: 0,
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100",
    },
    {
      id: 7,
      name: "James Oloo",
      email: "james.oloo@email.com",
      phone: "+254 723 000 007",
      property: "Karen Villas",
      propertyId: 3,
      unit: "V02",
      unitType: "3BR Villa",
      monthlyRent: 65000,
      leaseStart: new Date(2025, 5, 1),
      leaseEnd: new Date(2027, 4, 31),
      leaseStatus: "active",
      paymentStatus: "overdue",
      balance: 65000,
      avatar: null,
    },
    {
      id: 8,
      name: "Ann Muthoni",
      email: "ann.muthoni@email.com",
      phone: "+254 714 000 008",
      property: "Parklands Plaza",
      propertyId: 5,
      unit: "D05",
      unitType: "Retail",
      monthlyRent: 40000,
      leaseStart: new Date(2024, 11, 1),
      leaseEnd: new Date(2025, 10, 30),
      leaseStatus: "expired",
      paymentStatus: "overdue",
      balance: 120000,
      avatar: null,
    },
    {
      id: 9,
      name: "Thomas Kipchoge",
      email: "thomas.kipchoge@email.com",
      phone: "+254 701 000 009",
      property: "Lavington Heights",
      propertyId: 4,
      unit: "C03",
      unitType: "3BR",
      monthlyRent: 85000,
      leaseStart: new Date(2025, 2, 1),
      leaseEnd: new Date(2026, 1, 28),
      leaseStatus: "ending",
      paymentStatus: "paid",
      balance: 0,
      avatar: null,
    },
    {
      id: 10,
      name: "Lydia Chebet",
      email: "lydia.chebet@email.com",
      phone: "+254 716 000 010",
      property: "Westlands Towers",
      propertyId: 2,
      unit: "B12",
      unitType: "3BR",
      monthlyRent: 110000,
      leaseStart: new Date(2024, 0, 1),
      leaseEnd: new Date(2026, 11, 31),
      leaseStatus: "active",
      paymentStatus: "paid",
      balance: 0,
      avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=100",
    },
  ],

  financeData: {
    summary: {
      totalRevenue: 2450000,
      totalExpenses: 510000,
      netIncome: 1940000,
      revenueGrowth: 12.5,
      expenseGrowth: 2.0,
      netIncomeGrowth: 15.2,
      collectionRate: 94.3,
      ytdRevenue: 13150000,
      ytdExpenses: 2950000,
    },
    monthlyPnl: [
      { month: "Sep", revenue: 2100000, expenses: 450000, net: 1650000 },
      { month: "Oct", revenue: 2250000, expenses: 480000, net: 1770000 },
      { month: "Nov", revenue: 2300000, expenses: 490000, net: 1810000 },
      { month: "Dec", revenue: 2400000, expenses: 520000, net: 1880000 },
      { month: "Jan", revenue: 2350000, expenses: 500000, net: 1850000 },
      { month: "Feb", revenue: 2450000, expenses: 510000, net: 1940000 },
    ],
    expenseCategories: [
      { category: "Security", amount: 180000, percentage: 35, color: "#1A3626" },
      { category: "Maintenance", amount: 120000, percentage: 24, color: "#C9A843" },
      { category: "Utilities", amount: 80000, percentage: 16, color: "#2D6040" },
      { category: "Cleaning", amount: 60000, percentage: 12, color: "#4A8C6A" },
      { category: "Admin & Legal", amount: 40000, percentage: 8, color: "#6BAF8E" },
      { category: "Other", amount: 30000, percentage: 6, color: "#A8D4BC" },
    ],
    revenueByProperty: [
      { property: "Westlands Towers", revenue: 720000, target: 720000, rate: 100 },
      { property: "Lavington Heights", revenue: 612000, target: 680000, rate: 90 },
      { property: "Kilimani Apts", revenue: 495000, target: 540000, rate: 91.7 },
      { property: "Karen Villas", revenue: 375000, target: 450000, rate: 83.3 },
      { property: "Parklands Plaza", revenue: 248000, target: 360000, rate: 68.9 },
    ],
    recentTransactions: [
      { id: 1, type: "income", tenant: "Lydia Chebet", property: "Westlands Towers", unit: "B12", amount: 110000, date: new Date(2026, 2, 18), method: "M-Pesa", reference: "QBS8H4L2PM", category: "Rent" },
      { id: 2, type: "expense", description: "Monthly security — Kilimani", property: "Kilimani Apartments", amount: 80000, date: new Date(2026, 2, 17), method: "Bank Transfer", reference: "TRF2026031701", category: "Security" },
      { id: 3, type: "income", tenant: "David Ochieng", property: "Karen Villas", unit: "V03", amount: 75000, date: new Date(2026, 2, 17), method: "M-Pesa", reference: "QAT7G3K1NL", category: "Rent" },
      { id: 4, type: "income", tenant: "Thomas Kipchoge", property: "Lavington Heights", unit: "C03", amount: 85000, date: new Date(2026, 2, 16), method: "Bank Transfer", reference: "TRF2026031601", category: "Rent" },
      { id: 5, type: "expense", description: "Plumbing repairs — Westlands B05", property: "Westlands Towers", amount: 45000, date: new Date(2026, 2, 15), method: "Cash", reference: "EXP20260315", category: "Maintenance" },
      { id: 6, type: "income", tenant: "Grace Njeri", property: "Kilimani Apartments", unit: "A07", amount: 45000, date: new Date(2026, 2, 14), method: "M-Pesa", reference: "QAR6F2J8MK", category: "Rent" },
      { id: 7, type: "expense", description: "Water bill — Common areas Lavington", property: "Lavington Heights", amount: 35000, date: new Date(2026, 2, 12), method: "Bank Transfer", reference: "TRF2026031201", category: "Utilities" },
      { id: 8, type: "income", tenant: "Mary Wanjiru", property: "Westlands Towers", unit: "B05", amount: 90000, date: new Date(2026, 2, 10), method: "M-Pesa", reference: "QAQ5E1H7LJ", category: "Rent" },
    ],
  },
};

// Property Detail Data
export const propertyDetailData = {
  id: 1,
  name: "Kilimani Apartments",
  location: "Kilimani, Nairobi",
  address: "Argwings Kodhek Road, Kilimani",
  type: "Apartment Complex",
  yearBuilt: 2018,
  totalUnits: 12,
  occupiedUnits: 11,
  vacantUnits: 1,
  occupancyRate: 91.7,
  monthlyIncome: 540000,
  yearlyIncome: 6480000,
  propertyValue: 85000000,
  images: [
    "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
    "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
    "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
    "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
  ],
  mainImage: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",

  units: [
    { id: "A01", type: "2BR", floor: 1, rent: 45000, tenant: "John Kamau", status: "occupied", leaseEnd: new Date(2026, 11, 31) },
    { id: "A02", type: "2BR", floor: 1, rent: 45000, tenant: "Mary Njeri", status: "occupied", leaseEnd: new Date(2026, 8, 15) },
    { id: "A03", type: "3BR", floor: 1, rent: 55000, tenant: null, status: "vacant", leaseEnd: null },
    { id: "A04", type: "2BR", floor: 2, rent: 45000, tenant: "David Omondi", status: "occupied", leaseEnd: new Date(2027, 1, 28) },
    { id: "A05", type: "2BR", floor: 2, rent: 45000, tenant: "Grace Wanjiku", status: "occupied", leaseEnd: new Date(2026, 10, 30) },
    { id: "A06", type: "3BR", floor: 2, rent: 55000, tenant: "Peter Mwangi", status: "occupied", leaseEnd: new Date(2026, 7, 20) },
    { id: "A07", type: "2BR", floor: 3, rent: 45000, tenant: "Sarah Akinyi", status: "occupied", leaseEnd: new Date(2027, 2, 15) },
    { id: "A08", type: "2BR", floor: 3, rent: 45000, tenant: "James Kipchoge", status: "occupied", leaseEnd: new Date(2026, 9, 10) },
    { id: "A09", type: "3BR", floor: 3, rent: 55000, tenant: "Ann Muthoni", status: "occupied", leaseEnd: new Date(2026, 11, 5) },
    { id: "A10", type: "2BR", floor: 4, rent: 45000, tenant: "Thomas Oloo", status: "occupied", leaseEnd: new Date(2027, 0, 25) },
    { id: "A11", type: "2BR", floor: 4, rent: 45000, tenant: "Jane Wangari", status: "occupied", leaseEnd: new Date(2026, 8, 8) },
    { id: "A12", type: "3BR", floor: 4, rent: 55000, tenant: "Robert Kimani", status: "occupied", leaseEnd: new Date(2026, 10, 18) },
  ],

  amenities: [
    { name: "24/7 Security", icon: "shield" },
    { name: "Backup Generator", icon: "zap" },
    { name: "Water Supply", icon: "droplet" },
    { name: "Parking Space", icon: "car" },
    { name: "Elevator", icon: "move" },
    { name: "CCTV Surveillance", icon: "camera" },
  ],

  revenueHistory: [
    { month: "Sep 2025", collected: 495000, expected: 540000, rate: 91.7 },
    { month: "Oct 2025", collected: 540000, expected: 540000, rate: 100 },
    { month: "Nov 2025", collected: 495000, expected: 540000, rate: 91.7 },
    { month: "Dec 2025", collected: 540000, expected: 540000, rate: 100 },
    { month: "Jan 2026", collected: 540000, expected: 540000, rate: 100 },
    { month: "Feb 2026", collected: 495000, expected: 540000, rate: 91.7 },
  ],

  expenses: [
    { category: "Maintenance", amount: 45000, date: new Date(2026, 2, 15), description: "Plumbing repairs - Unit A05" },
    { category: "Security", amount: 80000, date: new Date(2026, 2, 1), description: "Monthly security services" },
    { category: "Utilities", amount: 35000, date: new Date(2026, 2, 5), description: "Water bill - Common areas" },
    { category: "Cleaning", amount: 20000, date: new Date(2026, 2, 10), description: "Common area cleaning" },
    { category: "Repairs", amount: 65000, date: new Date(2026, 1, 20), description: "Elevator maintenance" },
  ],

  maintenanceHistory: [
    {
      id: 1,
      unit: "A05",
      issue: "Plumbing leak in kitchen",
      tenant: "Grace Wanjiku",
      date: new Date(2026, 2, 15),
      status: "completed",
      cost: 15000,
      priority: "high"
    },
    {
      id: 2,
      unit: "A12",
      issue: "Air conditioning not cooling",
      tenant: "Robert Kimani",
      date: new Date(2026, 2, 10),
      status: "completed",
      cost: 25000,
      priority: "medium"
    },
    {
      id: 3,
      unit: "A07",
      issue: "Broken window lock",
      tenant: "Sarah Akinyi",
      date: new Date(2026, 2, 5),
      status: "in_progress",
      cost: 8000,
      priority: "high"
    },
  ],

  manager: {
    name: "Matty Otieno",
    phone: "+254 722 123 456",
    email: "matty@zariva.com",
  }
};

export const tenantData = {
  profile: {
    name: "Sarah Akinyi",
    email: "sarah.akinyi@email.com",
    phone: "+254 712 345 678",
    profileImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
  },

  currentLease: {
    property: "Lavington Heights",
    unit: "C08",
    unitType: "2 Bedroom Apartment",
    location: "Lavington, Nairobi",
    monthlyRent: 68000,
    leaseStart: new Date(2025, 0, 1),
    leaseEnd: new Date(2026, 11, 31),
    depositPaid: 136000,
    landlord: "Matty Otieno",
    landlordPhone: "+254 722 123 456",
    propertyImage: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400",
  },

  rentStatus: {
    currentMonthDue: 68000,
    dueDate: new Date(2026, 2, 5),
    status: "overdue", // "paid" | "pending" | "overdue"
    daysOverdue: 15,
    balance: 68000,
    nextPaymentDue: new Date(2026, 3, 5),
  },

  paymentHistory: [
    {
      id: 1,
      month: "February 2026",
      amount: 68000,
      paymentDate: new Date(2026, 1, 3),
      method: "M-Pesa",
      reference: "QBS8H4L2PM",
      status: "completed",
      receiptUrl: "#",
    },
    {
      id: 2,
      month: "January 2026",
      amount: 68000,
      paymentDate: new Date(2026, 0, 5),
      method: "M-Pesa",
      reference: "QAT7G3K1NL",
      status: "completed",
      receiptUrl: "#",
    },
    {
      id: 3,
      month: "December 2025",
      amount: 68000,
      paymentDate: new Date(2025, 11, 2),
      method: "Bank Transfer",
      reference: "TRF20251202-456",
      status: "completed",
      receiptUrl: "#",
    },
    {
      id: 4,
      month: "November 2025",
      amount: 68000,
      paymentDate: new Date(2025, 10, 4),
      method: "M-Pesa",
      reference: "QAR6F2J8MK",
      status: "completed",
      receiptUrl: "#",
    },
    {
      id: 5,
      month: "October 2025",
      amount: 68000,
      paymentDate: new Date(2025, 9, 1),
      method: "M-Pesa",
      reference: "QAQ5E1H7LJ",
      status: "completed",
      receiptUrl: "#",
    },
  ],

  maintenanceRequests: [
    {
      id: 1,
      issue: "Air conditioning not working",
      description: "The AC unit in the master bedroom stopped working yesterday. It makes a clicking sound but doesn't cool.",
      category: "HVAC",
      priority: "high",
      status: "in_progress",
      submittedDate: new Date(2026, 2, 15),
      assignedTo: "Tech Solutions Ltd",
      estimatedCompletion: new Date(2026, 2, 22),
      images: [],
    },
    {
      id: 2,
      issue: "Leaking kitchen faucet",
      description: "Kitchen faucet has been dripping for the past week. Wasting water.",
      category: "Plumbing",
      priority: "medium",
      status: "pending",
      submittedDate: new Date(2026, 2, 10),
      assignedTo: null,
      estimatedCompletion: null,
      images: [],
    },
    {
      id: 3,
      issue: "Broken bedroom window lock",
      description: "Window lock in second bedroom is broken. Security concern.",
      category: "Security",
      priority: "high",
      status: "completed",
      submittedDate: new Date(2026, 1, 25),
      assignedTo: "SecureFix Kenya",
      completedDate: new Date(2026, 2, 2),
      images: [],
    },
  ],

  utilities: [
    {
      type: "Water",
      lastReading: 1250,
      currentReading: 1285,
      consumption: 35,
      cost: 1750,
      billingMonth: "February 2026",
    },
    {
      type: "Electricity",
      lastReading: 5420,
      currentReading: 5680,
      consumption: 260,
      cost: 5200,
      billingMonth: "February 2026",
    },
    {
      type: "Internet",
      provider: "Safaricom Home Fiber",
      plan: "50 Mbps",
      cost: 3999,
      billingMonth: "February 2026",
    },
  ],

  notifications: [
    {
      id: 1,
      type: "payment",
      title: "Rent Payment Overdue",
      message: "Your rent payment for March is 15 days overdue. Please pay KES 68,000 immediately.",
      date: new Date(2026, 2, 20),
      read: false,
      priority: "urgent",
    },
    {
      id: 2,
      type: "maintenance",
      title: "Maintenance Update",
      message: "Your AC repair request has been assigned to Tech Solutions Ltd. Expected completion: Mar 22.",
      date: new Date(2026, 2, 16),
      read: false,
      priority: "normal",
    },
    {
      id: 3,
      type: "announcement",
      title: "Water Interruption Notice",
      message: "Scheduled water maintenance on March 25, 8 AM - 2 PM. Plan accordingly.",
      date: new Date(2026, 2, 18),
      read: true,
      priority: "normal",
    },
  ],

  documents: [
    {
      id: 1,
      type: "lease",
      title: "Tenancy Agreement 2025/2026",
      description: "Signed tenancy agreement for Lavington Heights, Unit C08",
      property: "Lavington Heights",
      unit: "C08",
      date: new Date(2025, 0, 1),
      expiryDate: new Date(2026, 11, 31),
      size: "2.4 MB",
      format: "PDF",
      url: "#",
      signed: true,
    },
    {
      id: 2,
      type: "receipt",
      title: "Rent Receipt — February 2026",
      description: "Official rent payment receipt for February 2026",
      property: "Lavington Heights",
      unit: "C08",
      date: new Date(2026, 1, 3),
      size: "128 KB",
      format: "PDF",
      url: "#",
      reference: "QBS8H4L2PM",
      amount: 68000,
    },
    {
      id: 3,
      type: "receipt",
      title: "Rent Receipt — January 2026",
      description: "Official rent payment receipt for January 2026",
      property: "Lavington Heights",
      unit: "C08",
      date: new Date(2026, 0, 5),
      size: "128 KB",
      format: "PDF",
      url: "#",
      reference: "QAT7G3K1NL",
      amount: 68000,
    },
    {
      id: 4,
      type: "receipt",
      title: "Rent Receipt — December 2025",
      description: "Official rent payment receipt for December 2025",
      property: "Lavington Heights",
      unit: "C08",
      date: new Date(2025, 11, 2),
      size: "128 KB",
      format: "PDF",
      url: "#",
      reference: "TRF20251202-456",
      amount: 68000,
    },
    {
      id: 5,
      type: "notice",
      title: "Rent Review Notice",
      description: "Annual rent review notice for the upcoming lease year",
      property: "Lavington Heights",
      unit: "C08",
      date: new Date(2026, 2, 1),
      size: "95 KB",
      format: "PDF",
      url: "#",
    },
    {
      id: 6,
      type: "notice",
      title: "Water Interruption Notice",
      description: "Scheduled maintenance on March 25, 2026",
      property: "Lavington Heights",
      unit: "All Units",
      date: new Date(2026, 2, 18),
      size: "64 KB",
      format: "PDF",
      url: "#",
    },
    {
      id: 7,
      type: "inventory",
      title: "Move-In Inventory Checklist",
      description: "Signed inventory and condition report at start of tenancy",
      property: "Lavington Heights",
      unit: "C08",
      date: new Date(2025, 0, 1),
      size: "1.1 MB",
      format: "PDF",
      url: "#",
      signed: true,
    },
    {
      id: 8,
      type: "receipt",
      title: "Security Deposit Receipt",
      description: "Receipt for security deposit paid at lease commencement",
      property: "Lavington Heights",
      unit: "C08",
      date: new Date(2025, 0, 1),
      size: "110 KB",
      format: "PDF",
      url: "#",
      amount: 136000,
    },
  ],
};
