export const landlordData = {
  overview: {
    totalProperties: 12,
    totalUnits: 48,
    occupiedUnits: 42,
    occupancyRate: 87.5,
    monthlyRevenue: 2450000,
    yearlyRevenue: 28500000,
    pendingMaintenance: 5,
    activeTenants: 42,
    revenueGrowth: 12.5,
    newTenantsThisMonth: 3,
  },

  properties: [
    {
      id: 1,
      name: "Kilimani Apartments",
      location: "Kilimani, Nairobi",
      units: 12,
      occupiedUnits: 11,
      occupancyRate: 91.7,
      monthlyIncome: 540000,
      image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=400",
      type: "Apartment",
      status: "active",
    },
    {
      id: 2,
      name: "Westlands Towers",
      location: "Westlands, Nairobi",
      units: 8,
      occupiedUnits: 8,
      occupancyRate: 100,
      monthlyIncome: 720000,
      image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400",
      type: "Commercial",
      status: "active",
    },
    {
      id: 3,
      name: "Karen Villas",
      location: "Karen, Nairobi",
      units: 6,
      occupiedUnits: 5,
      occupancyRate: 83.3,
      monthlyIncome: 450000,
      image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400",
      type: "Villa",
      status: "active",
    },
    {
      id: 4,
      name: "Lavington Heights",
      location: "Lavington, Nairobi",
      units: 10,
      occupiedUnits: 9,
      occupancyRate: 90,
      monthlyIncome: 680000,
      image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400",
      type: "Apartment",
      status: "active",
    },
    {
      id: 5,
      name: "Parklands Plaza",
      location: "Parklands, Nairobi",
      units: 12,
      occupiedUnits: 9,
      occupancyRate: 75,
      monthlyIncome: 360000,
      image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400",
      type: "Mixed Use",
      status: "maintenance",
    },
  ],

  revenueData: [
    { month: "Sep", revenue: 2100000, expenses: 450000 },
    { month: "Oct", revenue: 2250000, expenses: 480000 },
    { month: "Nov", revenue: 2300000, expenses: 490000 },
    { month: "Dec", revenue: 2400000, expenses: 520000 },
    { month: "Jan", revenue: 2350000, expenses: 500000 },
    { month: "Feb", revenue: 2450000, expenses: 510000 },
  ],

  recentActivity: [
    {
      id: 1,
      type: "payment",
      tenant: "John Kamau",
      property: "Kilimani Apartments",
      unit: "A12",
      amount: 45000,
      date: new Date(2026, 2, 18),
      status: "completed",
    },
    {
      id: 2,
      type: "maintenance",
      tenant: "Mary Wanjiru",
      property: "Westlands Towers",
      unit: "B05",
      description: "Plumbing issue in kitchen",
      date: new Date(2026, 2, 17),
      status: "pending",
    },
    {
      id: 3,
      type: "payment",
      tenant: "David Ochieng",
      property: "Karen Villas",
      unit: "V03",
      amount: 75000,
      date: new Date(2026, 2, 17),
      status: "completed",
    },
    {
      id: 4,
      type: "lease_renewal",
      tenant: "Sarah Akinyi",
      property: "Lavington Heights",
      unit: "C08",
      date: new Date(2026, 2, 16),
      status: "pending",
    },
    {
      id: 5,
      type: "payment",
      tenant: "Peter Mwangi",
      property: "Parklands Plaza",
      unit: "D02",
      amount: 30000,
      date: new Date(2026, 2, 15),
      status: "completed",
    },
    {
      id: 6,
      type: "maintenance",
      tenant: "Grace Njeri",
      property: "Kilimani Apartments",
      unit: "A07",
      description: "Air conditioning not working",
      date: new Date(2026, 2, 15),
      status: "in_progress",
    },
  ],

  maintenanceRequests: [
    {
      id: 1,
      property: "Westlands Towers",
      unit: "B05",
      tenant: "Mary Wanjiru",
      issue: "Plumbing issue in kitchen",
      priority: "high",
      status: "pending",
      date: new Date(2026, 2, 17),
    },
    {
      id: 2,
      property: "Kilimani Apartments",
      unit: "A07",
      tenant: "Grace Njeri",
      issue: "Air conditioning not working",
      priority: "medium",
      status: "in_progress",
      date: new Date(2026, 2, 15),
    },
    {
      id: 3,
      property: "Karen Villas",
      unit: "V02",
      tenant: "James Oloo",
      issue: "Broken window in bedroom",
      priority: "high",
      status: "pending",
      date: new Date(2026, 2, 14),
    },
    {
      id: 4,
      property: "Parklands Plaza",
      unit: "D05",
      tenant: "Ann Muthoni",
      issue: "Electrical outlet not working",
      priority: "low",
      status: "pending",
      date: new Date(2026, 2, 13),
    },
    {
      id: 5,
      property: "Lavington Heights",
      unit: "C03",
      tenant: "Thomas Kipchoge",
      issue: "Water heater malfunction",
      priority: "high",
      status: "in_progress",
      date: new Date(2026, 2, 12),
    },
  ],
};

// Property Detail Data
export const propertyDetailData = {
  id: 1,
  name: "Kilimani Apartments",
  location: "Kilimani, Nairobi",
  address: "Argwings Kodhek Road, Kilimani",
  type: "Apartment Complex",
  yearBuilt: 2018,
  totalUnits: 12,
  occupiedUnits: 11,
  vacantUnits: 1,
  occupancyRate: 91.7,
  monthlyIncome: 540000,
  yearlyIncome: 6480000,
  propertyValue: 85000000,
  images: [
    "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
    "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
    "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
    "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
  ],
  mainImage: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",

  units: [
    { id: "A01", type: "2BR", floor: 1, rent: 45000, tenant: "John Kamau", status: "occupied", leaseEnd: new Date(2026, 11, 31) },
    { id: "A02", type: "2BR", floor: 1, rent: 45000, tenant: "Mary Njeri", status: "occupied", leaseEnd: new Date(2026, 8, 15) },
    { id: "A03", type: "3BR", floor: 1, rent: 55000, tenant: null, status: "vacant", leaseEnd: null },
    { id: "A04", type: "2BR", floor: 2, rent: 45000, tenant: "David Omondi", status: "occupied", leaseEnd: new Date(2027, 1, 28) },
    { id: "A05", type: "2BR", floor: 2, rent: 45000, tenant: "Grace Wanjiku", status: "occupied", leaseEnd: new Date(2026, 10, 30) },
    { id: "A06", type: "3BR", floor: 2, rent: 55000, tenant: "Peter Mwangi", status: "occupied", leaseEnd: new Date(2026, 7, 20) },
    { id: "A07", type: "2BR", floor: 3, rent: 45000, tenant: "Sarah Akinyi", status: "occupied", leaseEnd: new Date(2027, 2, 15) },
    { id: "A08", type: "2BR", floor: 3, rent: 45000, tenant: "James Kipchoge", status: "occupied", leaseEnd: new Date(2026, 9, 10) },
    { id: "A09", type: "3BR", floor: 3, rent: 55000, tenant: "Ann Muthoni", status: "occupied", leaseEnd: new Date(2026, 11, 5) },
    { id: "A10", type: "2BR", floor: 4, rent: 45000, tenant: "Thomas Oloo", status: "occupied", leaseEnd: new Date(2027, 0, 25) },
    { id: "A11", type: "2BR", floor: 4, rent: 45000, tenant: "Jane Wangari", status: "occupied", leaseEnd: new Date(2026, 8, 8) },
    { id: "A12", type: "3BR", floor: 4, rent: 55000, tenant: "Robert Kimani", status: "occupied", leaseEnd: new Date(2026, 10, 18) },
  ],

  amenities: [
    { name: "24/7 Security", icon: "shield" },
    { name: "Backup Generator", icon: "zap" },
    { name: "Water Supply", icon: "droplet" },
    { name: "Parking Space", icon: "car" },
    { name: "Elevator", icon: "move" },
    { name: "CCTV Surveillance", icon: "camera" },
  ],

  revenueHistory: [
    { month: "Sep 2025", collected: 495000, expected: 540000, rate: 91.7 },
    { month: "Oct 2025", collected: 540000, expected: 540000, rate: 100 },
    { month: "Nov 2025", collected: 495000, expected: 540000, rate: 91.7 },
    { month: "Dec 2025", collected: 540000, expected: 540000, rate: 100 },
    { month: "Jan 2026", collected: 540000, expected: 540000, rate: 100 },
    { month: "Feb 2026", collected: 495000, expected: 540000, rate: 91.7 },
  ],

  expenses: [
    { category: "Maintenance", amount: 45000, date: new Date(2026, 2, 15), description: "Plumbing repairs - Unit A05" },
    { category: "Security", amount: 80000, date: new Date(2026, 2, 1), description: "Monthly security services" },
    { category: "Utilities", amount: 35000, date: new Date(2026, 2, 5), description: "Water bill - Common areas" },
    { category: "Cleaning", amount: 20000, date: new Date(2026, 2, 10), description: "Common area cleaning" },
    { category: "Repairs", amount: 65000, date: new Date(2026, 1, 20), description: "Elevator maintenance" },
  ],

  maintenanceHistory: [
    {
      id: 1,
      unit: "A05",
      issue: "Plumbing leak in kitchen",
      tenant: "Grace Wanjiku",
      date: new Date(2026, 2, 15),
      status: "completed",
      cost: 15000,
      priority: "high"
    },
    {
      id: 2,
      unit: "A12",
      issue: "Air conditioning not cooling",
      tenant: "Robert Kimani",
      date: new Date(2026, 2, 10),
      status: "completed",
      cost: 25000,
      priority: "medium"
    },
    {
      id: 3,
      unit: "A07",
      issue: "Broken window lock",
      tenant: "Sarah Akinyi",
      date: new Date(2026, 2, 5),
      status: "in_progress",
      cost: 8000,
      priority: "high"
    },
  ],

  manager: {
    name: "Matty Otieno",
    phone: "+254 722 123 456",
    email: "matty@zariva.com",
  }
};

export const tenantData = {
  profile: {
    name: "Sarah Akinyi",
    email: "sarah.akinyi@email.com",
    phone: "+254 712 345 678",
    profileImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
  },

  currentLease: {
    property: "Lavington Heights",
    unit: "C08",
    unitType: "2 Bedroom Apartment",
    location: "Lavington, Nairobi",
    monthlyRent: 68000,
    leaseStart: new Date(2025, 0, 1),
    leaseEnd: new Date(2026, 11, 31),
    depositPaid: 136000,
    landlord: "Matty Otieno",
    landlordPhone: "+254 722 123 456",
    propertyImage: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400",
  },

  rentStatus: {
    currentMonthDue: 68000,
    dueDate: new Date(2026, 2, 5),
    status: "overdue", // "paid" | "pending" | "overdue"
    daysOverdue: 15,
    balance: 68000,
    nextPaymentDue: new Date(2026, 3, 5),
  },

  paymentHistory: [
    {
      id: 1,
      month: "February 2026",
      amount: 68000,
      paymentDate: new Date(2026, 1, 3),
      method: "M-Pesa",
      reference: "QBS8H4L2PM",
      status: "completed",
      receiptUrl: "#",
    },
    {
      id: 2,
      month: "January 2026",
      amount: 68000,
      paymentDate: new Date(2026, 0, 5),
      method: "M-Pesa",
      reference: "QAT7G3K1NL",
      status: "completed",
      receiptUrl: "#",
    },
    {
      id: 3,
      month: "December 2025",
      amount: 68000,
      paymentDate: new Date(2025, 11, 2),
      method: "Bank Transfer",
      reference: "TRF20251202-456",
      status: "completed",
      receiptUrl: "#",
    },
    {
      id: 4,
      month: "November 2025",
      amount: 68000,
      paymentDate: new Date(2025, 10, 4),
      method: "M-Pesa",
      reference: "QAR6F2J8MK",
      status: "completed",
      receiptUrl: "#",
    },
    {
      id: 5,
      month: "October 2025",
      amount: 68000,
      paymentDate: new Date(2025, 9, 1),
      method: "M-Pesa",
      reference: "QAQ5E1H7LJ",
      status: "completed",
      receiptUrl: "#",
    },
  ],

  maintenanceRequests: [
    {
      id: 1,
      issue: "Air conditioning not working",
      description: "The AC unit in the master bedroom stopped working yesterday. It makes a clicking sound but doesn't cool.",
      category: "HVAC",
      priority: "high",
      status: "in_progress",
      submittedDate: new Date(2026, 2, 15),
      assignedTo: "Tech Solutions Ltd",
      estimatedCompletion: new Date(2026, 2, 22),
      images: [],
    },
    {
      id: 2,
      issue: "Leaking kitchen faucet",
      description: "Kitchen faucet has been dripping for the past week. Wasting water.",
      category: "Plumbing",
      priority: "medium",
      status: "pending",
      submittedDate: new Date(2026, 2, 10),
      assignedTo: null,
      estimatedCompletion: null,
      images: [],
    },
    {
      id: 3,
      issue: "Broken bedroom window lock",
      description: "Window lock in second bedroom is broken. Security concern.",
      category: "Security",
      priority: "high",
      status: "completed",
      submittedDate: new Date(2026, 1, 25),
      assignedTo: "SecureFix Kenya",
      completedDate: new Date(2026, 2, 2),
      images: [],
    },
  ],

  utilities: [
    {
      type: "Water",
      lastReading: 1250,
      currentReading: 1285,
      consumption: 35,
      cost: 1750,
      billingMonth: "February 2026",
    },
    {
      type: "Electricity",
      lastReading: 5420,
      currentReading: 5680,
      consumption: 260,
      cost: 5200,
      billingMonth: "February 2026",
    },
    {
      type: "Internet",
      provider: "Safaricom Home Fiber",
      plan: "50 Mbps",
      cost: 3999,
      billingMonth: "February 2026",
    },
  ],

  notifications: [
    {
      id: 1,
      type: "payment",
      title: "Rent Payment Overdue",
      message: "Your rent payment for March is 15 days overdue. Please pay KES 68,000 immediately.",
      date: new Date(2026, 2, 20),
      read: false,
      priority: "urgent",
    },
    {
      id: 2,
      type: "maintenance",
      title: "Maintenance Update",
      message: "Your AC repair request has been assigned to Tech Solutions Ltd. Expected completion: Mar 22.",
      date: new Date(2026, 2, 16),
      read: false,
      priority: "normal",
    },
    {
      id: 3,
      type: "announcement",
      title: "Water Interruption Notice",
      message: "Scheduled water maintenance on March 25, 8 AM - 2 PM. Plan accordingly.",
      date: new Date(2026, 2, 18),
      read: true,
      priority: "normal",
    },
  ],
};
